// Generated by tools/import_windows_strings.py from its PLATFORM_TEXTS table (plan §3.2); do not edit.

extension MenuText {
    /// The Windows English texts the Mac changes, and the Mac English text that is their catalog key.
    public static let macReplacements: [String: String] = [
        "Don't show Windows print dialog": "Don't show the system print dialog",
        "In tray menu show most recent tasks first": "In menu bar menu show most recent tasks first",
        "Left click to copy URL to clipboard. Right click to open URL.": "Click to copy URL to clipboard. Option-click to open URL.",
        "Minimize to tray on start": "Don't show the window at launch",
        "On tray icon double left click:": "On menu bar icon double left click:",
        "On tray icon left click:": "On menu bar icon left click:",
        "On tray icon middle click:": "On menu bar icon middle click:",
        "Run UpLa when Windows starts": "Run UpLa when you log in",
        "Show \"Edit with UpLa\" button in Windows Explorer context menu": "Show \"Edit with UpLa\" in Finder Quick Actions",
        "Show \"Upload with UpLa\" button in Windows Explorer context menu": "Show \"Upload with UpLa\" in Finder Quick Actions",
        "Show UpLa in \"Send to\" menu": "Show UpLa in the Share menu",
        "Show file in explorer": "Show file in Finder",
        "Show progress in taskbar button": "Show progress in Dock icon",
        "Show progress in tray icon": "Show progress in menu bar icon",
        "Show recent tasks in tray menu": "Show recent tasks in menu bar menu",
        "Show tray icon": "Show menu bar icon",
        "Toggle tray menu": "Toggle menu bar menu",
        "UpLa is minimized to the system tray.": "UpLa keeps running in the menu bar.",
        "Your anti-virus software or the controlled folder access feature in Windows could be blocking UpLa.": "UpLa may not be allowed to write to the folder; check System Settings › Privacy & Security."
    ]
}
